### ISSUE TITLE
Would Like To Update This Site

### ISSUE THREAD

**Issue by cryptostewie** [BryanEgbert/study_code#2]
Hello,

I would like to update this site and make it into a chrome extension. But I see it's a flutter web project. How did u host this on cPanel?

**Comment by BryanEgbert** [comment]
I cannot answer that myself, but i found a website that explains how to make it into a chrome extension, i think [this](https://medium.com/@dailyfluttermonster/how-to-create-a-flutter-chrome-extension-1293d75b887b) could help.

**Comment by cryptostewie** [comment]
Thanks I will look into it.

**Comment by cryptostewie** [comment]
I'm new to flutter which is the pop? Because there's a few folders which file is the main file for online?

**Comment by BryanEgbert** [comment]
The main folder to edit the web content is in the `lib` folder and in the `build` folder there is a `web` subfolder that made flutter web possible. Although i don't know why there is 2 web folders. Just in case, if you want to configure something related to that folder, edit them both.
EDIT: If you changed something in the lib folder. Make sure to run the command `flutter build web` in the terminal, or else, the website in the internet won't notice the change although you can view it in local host if you enter `flutter run` in the terminal

**Comment by cryptostewie** [comment]
Got It! I was able to make it into an App for All OS systems!

**Comment by cryptostewie** [comment]
Was thinking of making one for edpuzzle too

**Comment by BryanEgbert** [comment]
great, although for quizizz, i think the company put a security system to hide the real quiz ID and if you want to make one for other Q&A website, you need to hack through their API for the answer

**Comment by cryptostewie** [comment]
Yes I know, I sorta found a way to get it. Also do you have a discord?

**Comment by BryanEgbert** [comment]
yes, PlayerPlay#9549

**Comment by cryptostewie** [comment]
I added you im MrRobot

**Comment by BryanEgbert** [comment]
since you've added me in discord, i'll close this issue
